import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Geist 폰트 임포트 제거
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`font-sans antialiased`} // Tailwind CSS 기본 폰트 스택 사용
      >
        {children}
      </body>
    </html>
  );
}
